<div class="card" id="about">
    <h2>The 88MOB Legacy</h2>
    <p><strong>25 Years of Street Authority.</strong> Established in 1998, V3GASBOI is a Las Vegas independent powerhouse rooted in the Lyrical Mindz era.</p>
    <p>With over 9,000 plays in 35 countries, the movement is global. From the streets of Owens Ave to collaborations with legends like C-BO, the legacy is built on ownership and performance.</p>
    <div style="margin-top: 20px;">
        <span class="badge">EST. 1998</span>
        <span class="badge">LAS VEGAS ORIGIN</span>
        <span class="badge">88MOB ARCHITECT</span>
    </div>
</div>
